version: "3"

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-dcat}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: spork
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  eureka-server:
    image: macchiato23/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
  apigw:
    image: macchiato23/apigw:curly-spork-0.0.3
    container_name: apigw
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - zipkin
      - eureka-server

#  youtube:
#    image: macchiato23/youtube:curly-spork-0.0.3
#    container_name: youtube
#    ports:
#      - "8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    volumes:
#      - "./tokens:/tokens"
#    networks:
#      - spring
#      - postgres
#    depends_on:
#      - zipkin
#      - postgres

  media:
    image: macchiato23/media:latest
    container_name: media
    ports:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - media:/tmp
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres

  courses:
    image: macchiato23/courses:curly-spork-0.0.4
    container_name: courses
    ports:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - courses:/app/trans
    networks:
      - spring
      - postgres
    depends_on:
      - zipkin
      - postgres

#  pgadmin:
#   container_name: pgadmin
#   image: dpage/pgadmin4
#   environment:
#     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
#     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
#     PGADMIN_CONFIG_SERVER_MODE: 'False'
#   volumes:
#     - pgadmin:/var/lib/pgadmin
#   ports:
#     - "5050:80"
#   networks:
#     - postgres
#   restart: unless-stopped

  #  notification:
  #    image: macchiato23/notification:latest
  #    container_name: notification
  #    ports:
  #      - "8082:8082"
  #    environment:
  #      - SPRING_PROFILES_ACTIVE=docker
  #    networks:
  #      - spring
  #      - postgres
  #    depends_on:
  #      - zipkin
  #      - postgres
  #      - rabbitmq

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin:
  media:
  courses: