server:
  port: 8080

spring:
  application:
    name: courses

  datasource:
    username: ${POSTGRES_USER:dcat}
    password: ${POSTGRES_PASSWORD:password}
    url: jdbc:postgresql://postgres:5432/spork

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

management:
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
