
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: youtube
            uri: lb://YOUTUBE
            predicates:
              - Path=/youtube/**
            filters:
              - PrefixPath=/api/v1

management:
  zipkin:
    tracing:
      endpoint: http://localhost:9412/api/v2/spans
  tracing:
    sampling:
      probability: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}


logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO